version: "3.0"

services:
  backend:
    volumes:
      - ./backend:/app
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - 8080:8080

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./frontend:/src # ローカルをコンテナ内にマウント
    command: sh -c "cd /src && yarn dev" #コンテナを立ち上げたときに自動的にbuildする
    ports:
      - "3000:3000"
 
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf