services:
  backend:
    volumes:
      - ./backend:/app
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - 8080:8080
      - 8000:8000

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      target: development
    volumes:
      - ./frontend:/src
      - node_modules:/src/node_modules
    command: sh -c "cd /src && yarn dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
 
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # rootアカウントをパスワードなしで作成
      MYSQL_DATABASE: 'demo'  # 初期データベースとしてdemoを設定
      TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    ports:
      - 33306:3306  # ホストマシンのポート33306を、docker内のポート3306に接続する
      
  test_db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # rootアカウントをパスワードなしで作成
      MYSQL_DATABASE: 'test_demo'  # 初期データベースとしてtest_demoを設定
      TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定
    volumes:
      - mysql_test_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    ports:
      - 33307:3306 
volumes:
  mysql_data:
  mysql_test_data:
  node_modules: