name: Python Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: 'demo'
          TZ: 'Asia/Tokyo'
        ports:
          - 33307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/backend/requirements.txt
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}/backend:/app/src
        DATABASE_URL: mysql://root:@localhost:33307/demo
      run: |
        pytest