name: Python Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      test_db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: test_db
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/backend/requirements.txt
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}/backend:/app/src
        FITBIT_CLIENT_ID: ${{ secrets.FITBIT_CLIENT_ID }}
        FITBIT_CLIENT_SECRET: ${{ secrets.FITBIT_CLIENT_SECRET }}
        FITBIT_REDIRECT_URI: ${{ secrets.FITBIT_REDIRECT_URI }}
        FITBIT_AUTHORIZATION_URI: ${{ secrets.FITBIT_AUTHORIZATION_URI }}
        FITBIT_REFRESH_TOKEN_URI: ${{ secrets.FITBIT_REFRESH_TOKEN_URI }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_CHARSET: ${{ secrets.DB_CHARSET }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_FROM: ${{ secrets.MAIL_FROM }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
        MAIL_STARTTLS: ${{ secrets.MAIL_STARTTLS }}
        MAIL_SSL_TLS: ${{ secrets.MAIL_SSL_TLS }}
        USE_CREDENTIALS: ${{ secrets.USE_CREDENTIALS }}
        VALIDATE_CERTS: ${{ secrets.VALIDATE_CERTS }}
      run: |
        pytest